// Licensed under CC-BY-4.0 (<https://creativecommons.org/licenses/by/4.0/>)

= STF Core: Documentation
Mars <mars@squirrel.pub>
v0.0.0
:homepage: https://github.com/emperorofmars/stf
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:library: Asciidoctor
:toc:
:toclevels: 4
:toc-placement!:
:idprefix:
:idseparator: -
:experimental:
:table-caption!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

**Squirrel Transfer Format - Experimental Modular 3D Interchange Format** [version {revnumber}]

Intended for (not only) game development use-cases.

toc::[]

== Introduction
An STF asset can be represented as a single binary file, containing a Json definition and a set of binary buffers.

Alternatively and optionally, an STF assset can be separated into a Json file containing the definition, and multiple buffer files. This is not required to be implemented for a valid STF implementation.

By itself, STF defines merely a 'shell' format. Actual content is stored in `resources` defined by their `type`. Support for importing, exporting & validationg a resource is implemented by a `module`.

The minimum required set of modules is specified in link:./modules.adoc[Modules], as well as some additional not-required modules.

STF implementations must provide an easy to use plugin system for modules, and if in any way possible, the ability to hot-load modules.

Objects of any type get referenced by a unique ID as a string. This will be refered to as `ID`. Usually it should be an UUID v4.

.Key Facts
* The file extension for stf binary files is `.stf`.
* The file extension for stf Json files is `.stf.json`.
* The media-type for stf binary files is `model/stf+binary`.
* The media-type for stf json files is `model/stf+json`.
* The STF binary header is stored in `little endian` byte order.
* By default, binary buffers are stored in `little endian` byte order.
* The Json definition is encoded as `utf8`.
* STF uses the same coordinate system as glTF 2.0. (See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units[glTF-2.0. coordinate-system-and-units])

== Binary Format
An STF binary file consists of a binary header, a <<json-definition>>, and zero or more binary buffers.

.Binary file layout
[%autowidth, %header,cols=2*]
|===
|Length (Bytes) |Content
|4 | Magic number: `STF0`
|4 | STF binary format version major
|4 | STF binary format version minor
|4 | Number of buffers, including the Json definiton buffer
|8 * {number of buffers} | Buffer length in bytes
|{number of buffers} * {buffer length} | The buffers
|===

The Json definition is the first and only required buffer.

== Json Definition
The root Json element is an object. It contains 3 properties: `<<stf>>`, `<<resources>>` and `<<buffers>>`.

=== stf
The `stf` object holds meta information.

.`stf` object properties:
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|version_major |Yes |Integer |Major version of STF
|version_minor |Yes |Integer |Minor version of STF
|root |Yes |ID |ID of the root resource
|profiles |No |List<String> |List of <<profiles, profiles>> this asset adheres to.
|meta |No |Object<String, String> |Meta information such as authors, license or documentation link.
|metric_multiplier |No |Float |Which number represents one meter. The default value is `1.0`.
|===

The root resource must be of the xref:./modules_core/data/stf_prefab.adoc[`stf-prefab`] type. It represents the assets hierarchy and has a single root node.

.Example
[%collapsible]
====
.stf object example
[,json]
----
"stf": {
	"version_major": 0,
	"version_minor": 0,
	"meta": {
		"asset_name": "STF Example 1"
	},
	"profiles": [
		"compatibility_wide"
	],
	"metric_multiplier": 1.0,
	"root": "5f1ea7e8-ee26-46c9-91dc-cd002cb9b0a5"
}
----
====

=== resources
The `resources` object is a map of resource objects identified by an ID.

The various resource objects describe the files actual content. Each resource has a `type` property and optional lists of references to other resources and buffers. Any further properties are defined by the definition for the resource.

.Resource object general properties:
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|type |Yes |String |Namespaced type name of the resource.
|referenced_resources |No |List<ID> |IDs of Resources this resource depends on.
|referenced_buffers |No |List<ID> |IDs of Buffers this resource depends on.
|name |No |String |Display name of the resource.
|version_major |No |Integer |Major version of this resource. The default value is `0`.
|version_minor |No |Integer |Major version of this resource. The default value is `0`.
|degraded |No |Boolean |Has this resource lost information at some point, but retained the same ID. The default is `False`.
|===

Resources may be composed of other resources if the relationship is 1 to 1. This is the case for components.
Every resource has to list all references to buffers and resources it uses.

Resources can be `Data`, `Node` and `Component` kinds.
Each of these kinds has additional properties.

==== Data
Data resources can be instantiated.
Suppport for loading module plugins of this kind is required.

.Data resource properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|fallback |No |ID |ID of a resource that should be used in case this one's type is not supported in this implementation
|components |No |Map<ID, Component> |
|===

==== Node
Root nodes must be referenced by a `data` resource, usually `stf.prefab`.
Node resources can not be instantiated. Only the parent of the entire hierarchy of nodes can be.
Suppport for loading module plugins of this kind is required.
All node kinds must be super-sets of `stf.node` or `stf.bone`.

.Node resource properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|enabled |No |boolean |True by default
|children |No |Map<ID, Node> |
|parent_binding |No |List<ID> |
|components |No |Map<ID, Component> |
|instance |No |ID |
|===

==== Instance
Instances have a 1 to 1 relationship to nodes. They represent an instance of a `data` resource on in the scene hierarchy. These include for example mesh or armature instances.
Instances can provide data relevant for the instance of the resource, such as an armatures pose or meshes blendshape value or material assignments.

.Instance resource properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|enabled |No |boolean |True by default
|===

==== Component
Represents additional functionality or information for `Data` or `Node` kinds.
Component resources can not be instantiated. Component resources must be stored within `Data` or `Node` kinds and can not exist on the top level `resources` object.
Suppport for loading module plugins of this kind is required.

.Component resource properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|enabled |No |boolean |True by default
|overrides |No |List<ID> |References `Component` kind types that should not be processed, if this type is supported
|===

==== Resource Composition Examples
xref:./modules_core/data/stf_image.adoc[`stf.image`] is a `Data` kind. `Data` kinds can only exist at the top level.
xref:./modules_core/node/stf_node_spatial.adoc[`stf.node.spatial`] is a `Node` kind. `Node` kinds can only exist within `Data` kinds.

The information about what `kind` a type is must be known by a type's implementation and is not contained in STF files. This information should be used to validate STF files.

.Example
[%collapsible]
====
.resources object example
[,json]
----
"resources": {
	"b5f96f63-d5ce-4210-b4d6-8f43fbf557dd": {
		"type": "stf.material",
		"name": "Body Material",
		"referenced_resources": [
			"6f03d810-4613-467d-921b-a5302552f9d5"
		],
		"properties": {
			"albedo": {
				"type": "image",
				"image": 6f03d810-4613-467d-921b-a5302552f9d5
			},
		}
	},
	"6f03d810-4613-467d-921b-a5302552f9d5": {
		"type": "stf.image",
		"name": "Body_Albedo",
		"image_format": "png",
		"texture_type": "rgb",
		"components": {
			"3ca7f62c-b2a8-4315-bb1d-e4c6118ead70": {
				"type": "stf.texture",
				"resolution": [2048, 2048],
				"compression": "BC7",
				"texture_type": "color",
				"downscale_priority": 0
			}
		}
	},
}
----
====

=== buffers
The `buffers` object is a map of buffer objects identified by an ID.
Each buffer object has a `type` property. Any further properties are defined in the buffer-type's definition.
Two types of buffers are defined. Supporting buffer plugins is not required.

In a binary STF file, `stf.buffer.included` is the only supported buffer type.

In a `stf.json` file, `stf.buffer.file` is the only supported buffer type.

Buffers which are fetched by URL may be considered in the future.

==== stf.buffer.included
This type represents a buffer contained in the same file.

.stf.buffer.included properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|index |Yes |Integer |Index of the binary buffer in the file
|===

.Example
[%collapsible]
====
.buffers object example in an STF binary file
[,json]
----
"buffers": {
	"2c04d7f9-96cd-4867-baf3-2a54d4d31a67": {
		"type": "stf.buffer.included",
		"index": 0
	}
}
----
====

==== stf.buffer.file
This type represents a buffer contained in the same file. Supporting this buffer-type is not required, but may be useful for version-controlled projects containing STF assets.

.stf.buffer.file properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|path |Yes |String |Relative path to a buffer file.
|===

An `.stfbuffer` file starts with a magic number of `STFB`. The rest of the file is the raw buffer.

.Example
[%collapsible]
====
.buffers object example in an STF Json file
[,json]
----
"buffers": {
	"2c04d7f9-96cd-4867-baf3-2a54d4d31a67": {
		"type": "stf.buffer.file",
		"path": "./buffers/mesh.stfbuffer"
	}
}
----
====

==== stf.buffer.json_array
This type stores binary data as an array directly. Supporting this buffer-type is not required, but may be useful during development.

.stf.buffer.json_array properties
[%autowidth, %header,cols=4*]
|===
|Key |Required |Type |Description

|data |Yes |String |Base64 encoded binary data
|===

.Example
[%collapsible]
====
.buffers object example in an STF Json file
[,json]
----
"buffers": {
	"2c04d7f9-96cd-4867-baf3-2a54d4d31a67": {
		"type": "stf.buffer.json_array",
		"data": [3, 0.34, 0.43214, 4.234, 4, 0.65, 0.6656, 2.234]
	}
}
----
====

=== Minimal Definition Example
.Show
[%collapsible]
====
[,json]
----
{
	"stf": {
		"version_major": 0,
		"version_minor": 0,
		"root": "8a4019a2-ca1d-4f9b-a316-b118cd31dada",
		"profiles": [],
		"asset_info": {
			"asset_name": "Default Cube"
		},
		"generator": "stfblender",
		"timestamp": "2025-02-15T20:41:01.988159+00:00",
		"metric_multiplier": 1
	},
	"resources": {
		"ba0f6e23-cb13-4cd5-9f66-8184460befc4": {
			"type": "stf.material",
			"name": "Material",
			"properties": {
				"color": {
					"value_type": "color",
					"value": [
						1.0,
						1.0,
						1.0
					]
				}
			},
			"referenced_resources": [],
			"referenced_buffers": [],
			"style_hints": [],
			"shader_targets": {}
		},
		"a72729cd-be7d-4b2c-a02e-cf8bfdc97e20": {
			"type": "stf.mesh",
			"name": "Cube",
			"referenced_resources": [],
			"referenced_buffers": [
				"d8e72e40-9006-441b-a0c5-1315700f14ef",
				"f36cb7a4-ffd9-48e7-87b3-321c91da6c5a",
				"2eb9be5e-b2ad-4df0-9163-942a506ddff8",
				"d12eb259-c0f3-4b0a-bed1-6904e62f8a1b",
				"4d9ee4ba-a45c-4bba-8a96-1bd79d86eee6",
				"a66be574-6ed2-4607-9190-a1ed4e2331c3",
				"cd1688fc-d100-4916-a0c2-dfa5899f010e",
				"0a0e9df2-e63e-47b5-acab-1435d5b3579f",
				"950f09cc-f6e1-4173-bf9a-2054ae233717",
				"85cc4f16-0934-45f0-9249-304a991ee78a",
				"d86f7202-ad21-4e94-8659-9f17c2be827b"
			],
			"material_slots": [
				"ba0f6e23-cb13-4cd5-9f66-8184460befc4"
			],
			"vertex_count": 8,
			"vertex_width": 4,
			"vertex_indices_width": 4,
			"vertices": "d8e72e40-9006-441b-a0c5-1315700f14ef",
			"vertex_color_width": 4,
			"colors": [],
			"split_count": 24,
			"split_indices_width": 4,
			"split_normal_width": 4,
			"split_tangent_width": 4,
			"split_color_width": 4,
			"split_uv_width": 4,
			"splits": "f36cb7a4-ffd9-48e7-87b3-321c91da6c5a",
			"split_normals": "2eb9be5e-b2ad-4df0-9163-942a506ddff8",
			"split_tangents": "d12eb259-c0f3-4b0a-bed1-6904e62f8a1b",
			"uvs": [
				{
					"name": "UVMap",
					"uv": "4d9ee4ba-a45c-4bba-8a96-1bd79d86eee6"
				}
			],
			"split_colors": [],
			"tris_count": 12,
			"face_count": 6,
			"face_indices_width": 4,
			"tris": "a66be574-6ed2-4607-9190-a1ed4e2331c3",
			"material_indices_width": 4,
			"faces": "cd1688fc-d100-4916-a0c2-dfa5899f010e",
			"material_indices": "0a0e9df2-e63e-47b5-acab-1435d5b3579f",
			"sharp_face_indices_len": 6,
			"sharp_face_indices": "950f09cc-f6e1-4173-bf9a-2054ae233717",
			"lines_len": 0,
			"lines": "85cc4f16-0934-45f0-9249-304a991ee78a",
			"sharp_edges_len": 0,
			"sharp_edges": "d86f7202-ad21-4e94-8659-9f17c2be827b",
			"armature": "a72729cd-be7d-4b2c-a02e-cf8bfdc97e20",
			"bones": [],
			"bone_weight_width": 4,
			"weights": [],
			"components": {
				"a72729cd-be7d-4b2c-a02e-cf8bfdc97e20": {
					"type": "stf.mesh.seams",
					"referenced_resources": [],
					"referenced_buffers": [
						"3f877195-7da8-41fc-be16-63833584fc97"
					],
					"seams_len": 0,
					"seams": "3f877195-7da8-41fc-be16-63833584fc97"
				}
			}
		},
		"4a76690a-8f1c-4a3c-9135-4bcac5c92831": {
			"type": "stf.instance.mesh",
			"name": "Cube",
			"children": [],
			"trs": [
				[
					0.0,
					0.0,
					-0.0
				],
				[
					0.0,
					0.0,
					-0.0,
					1.0
				],
				[
					1.0,
					1.0,
					1.0
				]
			],
			"instance": {
				"mesh": "a72729cd-be7d-4b2c-a02e-cf8bfdc97e20",
				"material_slots": [
					{
						"name": "Material",
						"material": "ba0f6e23-cb13-4cd5-9f66-8184460befc4"
					}
				],
				"blendshape_values": []
			},
			"referenced_resources": [],
			"referenced_buffers": []
		},
		"8a4019a2-ca1d-4f9b-a316-b118cd31dada": {
			"type": "stf.prefab",
			"name": "Scene Collection",
			"root_nodes": [
				"4a76690a-8f1c-4a3c-9135-4bcac5c92831"
			],
			"animations": [],
			"referenced_resources": [],
			"referenced_buffers": []
		}
	},
	"buffers": {
		"d8e72e40-9006-441b-a0c5-1315700f14ef": {
			"type": "stf.buffer.included",
			"index": 0
		},
		...
	}
}
----
====
