[book]
authors = ["Mars (https://squirrelbite.com)"]
language = "en"
src = "src"
title = "STF Documentation"
description = "Squirrel Transfer Format - A modular file-format for 3D assets"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
site-url = "https://docs.stfform.at"
cname = "documentation.stfform.at"
git-repository-icon = "fa-code-fork"
git-repository-url = "https://codeberg.org/emperorofmars/stf_documentation"
edit-url-template = "https://codeberg.org/emperorofmars/stf_documentation/_edit/master/{path}"
input-404 = "404.md"
additional-css = ["./theme/mdbook-admonish.css", "./theme/stf.css"]
copy-fonts = true

[output.html.fold]
enable = true
level = 1

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4

[preprocessor.gitinfo]
enable = true
template = "Date: {{date}}{{sep}}branch: {{branch}}{{sep}}commit: {{hash}}"
separator = " • "
font-size = "0.8em"
date-format = "%Y-%m-%d"
time-format = "%H:%M:%S"
branch = "master"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0" # do not edit: managed by `mdbook-admonish install`
