= STF: Documentation
:homepage: https://github.com/emperorofmars/stf
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

**Squirrel Transfer Format - Experimental Modular 3D Interchange Format** [version 0.0.0]

Intended for (not only) game development use-cases.

[cols=4*, frame=none, grid=none]
[%autowidth]
|===
|**In development for:**
|**https://github.com/emperorofmars/stf_blender[Blender]**
|**https://github.com/emperorofmars/stf_unity[Unity]**
|Godot (TBD soon)
|===

Very relevant future implementation targets include: 3dsMax, Unreal Engine, Maya, Bevy, BabylonJs, ...

---

This repository hosts the documentation for the core format and core modules.

[cols=3*, frame=none, grid=none]
[%autowidth]
|===
|**link:./docoumentation/stf_documentation.adoc[Core Format Documentation]**
|**link:./docoumentation/modules.adoc[Modules Documentation]**
|**link:./stf_roadmap.adoc[Roadmap]**
|===

== Concept
STF by itself is merely a shell format. It provides a framework for different modules to parse and serialize resourses.

STF doesn't hard code any specific resource types, however a few modules, including but not limited to `stf.mesh`, `stf.node` and `stf.material`, are provided by default.

Additional modules can be easily implemented by third parties. Module types, aside from the default ones, should use reverse domain notation for their type.

Similar to GLTF 2.0, an STF file consists of a Json definition and binary buffers. However, STF is firmly intended for interchange of 3d assets, not runtime loading or streaming.
Game-engines are responsible for runtime optimization, not the 3d file format or 3d modeling tool.

== Core Principles
* Fully modular and extensible
* Doesn't impose any artificial limitations on artists and game-developers
* Prioritizes developer & user-experience over performance and filesize
* Maximizes development speed for STF implementations as well as third party modules

---

Previously, a proof-of-concept for such a format has been made here: https://github.com/emperorofmars/stf-unity-poc[Repository Link]

---

.Minimal example Json definition
[%collapsible]
====
[,json]
----
{
	"stf": {
		"version_major": 0,
		"version_minor": 0,
		"root": "c46be810-c8d5-4b41-9302-be189ae8edca",
		"profiles": [],
		"asset_info": {
			"asset_name": "Default Cube"
		},
		"generator": "stfblender",
		"timestamp": "2025-03-27T18:41:43.530040+00:00",
		"metric_multiplier": 1
	},
	"resources": {
		"7bf9d0ed-6377-48bc-b764-ab72aefebfa6": {
			"type": "stf.material",
			"name": "Material",
			"properties": {
				"color": {
					"value_type": "color",
					"value": [
						1.0,
						1.0,
						1.0
					]
				}
			},
			"style_hints": [],
			"shader_targets": {}
		},
		"cef2b7a2-e4da-4762-9ba8-362cc441a6cf": {
			"type": "stf.mesh",
			"name": "Cube",
			"material_slots": [
				"7bf9d0ed-6377-48bc-b764-ab72aefebfa6"
			],
			"vertex_count": 8,
			"vertex_width": 4,
			"vertex_indices_width": 4,
			"vertices": "066d87ce-14af-4363-864b-de3f3b1fbf4d",
			"vertex_color_width": 4,
			"colors": [],
			"split_count": 24,
			"split_indices_width": 4,
			"split_normal_width": 4,
			"split_tangent_width": 4,
			"split_color_width": 4,
			"split_uv_width": 4,
			"splits": "e18e0731-0a8b-4b96-aab6-ce047418ec8f",
			"split_normals": "afbaef7d-5a37-419e-ba52-866acaeca43c",
			"split_tangents": "2629b0ca-9bd9-42dc-b305-6198ca2f355b",
			"uvs": [
				{
					"name": "UVMap",
					"uv": "77a96387-7301-4914-b120-9dfb4189e78a"
				}
			],
			"split_colors": [],
			"tris_count": 12,
			"face_count": 6,
			"face_indices_width": 4,
			"tris": "04b1027d-9c51-4753-a3be-069d434bc36c",
			"material_indices_width": 4,
			"faces": "f3a9b48a-295a-45a9-b3e7-d5eef488cfa9",
			"material_indices": "72eb1af2-094f-4a02-bd56-0332c06eb4b5",
			"sharp_face_indices_len": 6,
			"sharp_face_indices": "ea7006b3-c70d-4cae-aac4-2245df157169",
			"lines_len": 0,
			"lines": "55e7a01b-1028-4e0e-b277-49f4b3671f87",
			"sharp_edges_len": 0,
			"sharp_edges": "a64e4ba0-5211-4eaf-a808-700bf963d71e",
			"components": [
				"fcdc99bb-b7d1-420c-a9bd-8bbfc4d78673"
			]
		},
		"fcdc99bb-b7d1-420c-a9bd-8bbfc4d78673": {
			"type": "stf.mesh.seams",
			"seams_len": 0,
			"seams": "82888e68-585d-4cfc-8381-0f7bb7298ef5"
		},
		"3f1ea70d-7f31-48e3-a9ce-e619958812cf": {
			"type": "stf.instance.mesh",
			"mesh": "cef2b7a2-e4da-4762-9ba8-362cc441a6cf",
			"material_slots": [
				{
					"name": "Material",
					"material": "7bf9d0ed-6377-48bc-b764-ab72aefebfa6"
				}
			],
			"blendshape_values": []
		},
		"e3cd1a73-16b1-4702-968c-1f759ed4746f": {
			"type": "stf.node",
			"name": "Cube",
			"children": [],
			"trs": [
				[
					0.0,
					0.0,
					-0.0
				],
				[
					0.0,
					0.0,
					-0.0,
					1.0
				],
				[
					1.0,
					1.0,
					1.0
				]
			],
			"instance": "3f1ea70d-7f31-48e3-a9ce-e619958812cf"
		},
		"3394fbfe-1f05-4f75-889f-90450a8be02a": {
			"type": "stf.node",
			"name": "Light",
			"children": [],
			"trs": [
				[
					4.076245307922363,
					5.903861999511719,
					-1.0054539442062378
				],
				[
					0.16907574236392975,
					0.7558803558349609,
					-0.27217137813568115,
					0.570947527885437
				],
				[
					1.0,
					1.0,
					0.9999999403953552
				]
			]
		},
		"dd015e94-898b-4d7f-8b23-32504af51739": {
			"type": "stf.node",
			"name": "Camera",
			"children": [],
			"trs": [
				[
					7.358891487121582,
					4.958309173583984,
					6.925790786743164
				],
				[
					0.483536034822464,
					0.33687159419059753,
					-0.20870360732078552,
					0.7804827094078064
				],
				[
					1.0,
					1.0,
					1.0
				]
			]
		},
		"c46be810-c8d5-4b41-9302-be189ae8edca": {
			"type": "stf.prefab",
			"name": "Collection",
			"root_nodes": [
				"e3cd1a73-16b1-4702-968c-1f759ed4746f",
				"3394fbfe-1f05-4f75-889f-90450a8be02a",
				"dd015e94-898b-4d7f-8b23-32504af51739"
			],
			"animations": []
		}
	},
	"buffers": {
		"066d87ce-14af-4363-864b-de3f3b1fbf4d": {
			"type": "stf.buffer.included",
			"index": 0
		},
		"e18e0731-0a8b-4b96-aab6-ce047418ec8f": {
			"type": "stf.buffer.included",
			"index": 1
		},
		"afbaef7d-5a37-419e-ba52-866acaeca43c": {
			"type": "stf.buffer.included",
			"index": 2
		},
		"2629b0ca-9bd9-42dc-b305-6198ca2f355b": {
			"type": "stf.buffer.included",
			"index": 3
		},
		"77a96387-7301-4914-b120-9dfb4189e78a": {
			"type": "stf.buffer.included",
			"index": 4
		},
		"04b1027d-9c51-4753-a3be-069d434bc36c": {
			"type": "stf.buffer.included",
			"index": 5
		},
		"f3a9b48a-295a-45a9-b3e7-d5eef488cfa9": {
			"type": "stf.buffer.included",
			"index": 6
		},
		"72eb1af2-094f-4a02-bd56-0332c06eb4b5": {
			"type": "stf.buffer.included",
			"index": 7
		},
		"ea7006b3-c70d-4cae-aac4-2245df157169": {
			"type": "stf.buffer.included",
			"index": 8
		},
		"55e7a01b-1028-4e0e-b277-49f4b3671f87": {
			"type": "stf.buffer.included",
			"index": 9
		},
		"a64e4ba0-5211-4eaf-a808-700bf963d71e": {
			"type": "stf.buffer.included",
			"index": 10
		},
		"82888e68-585d-4cfc-8381-0f7bb7298ef5": {
			"type": "stf.buffer.included",
			"index": 11
		}
	}
}
----
====

== License
This repository is licensed under **CC-BY-4.0** (<https://creativecommons.org/licenses/by/4.0/>)
