= STF: Documentation
:homepage: https://github.com/emperorofmars/stf
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

In this repository the various parts that make up a 3d interchange format, intended for (not only) game development use-cases.

This fictional fileformat will be called:
**STF - Squirrel Transfer Format**
_Just to have a name to refer to._

Intended for (not only) game development use-cases.

Similar to the concept of GLTF 2.0, this format consists of a Json definition and binary buffers. However, this format is firmly intended for interchange, not runtime loading.

It doesn't hard-code any specific resource types like GLTF. It consists of a structure of resources which get identified by a 'type' property. Support for any arbitrary type gets implemented by modules, which should be pluggable and hot-loadable.

.Core Principles
* Highly modular and extensible.
* Doesn't impose any descisions on you.
* If something can work, it should work.

This is being explored datamodel first. Implementations may follow at some point.
A proof-of-concept has been made here: https://github.com/emperorofmars/stf-unity-poc[Repository Link]

⭐ Star this repo if you would like to not loose half your work between export and import! ⭐

---

[cols=2*, frame=none, grid=none]
[%autowidth]
|===
|**link:./docoumentation/stf_documentation.adoc[Core Format Documentation]**
|**link:./docoumentation/core_resources.adoc[Core Resources]**
|**link:./stf_roadmap.adoc[Roadmap]**
|===

.Minimal example Json definition
[%collapsible]
====
[,json]
----
{
	"stf": {
		"version_major": 0,
		"version_minor": 0,
		"meta": {
			"asset_name": "STF Example 1"
		},
		"profiles": [
			"compatibility_wide"
		],
		"root": "5f1ea7e8-ee26-46c9-91dc-cd002cb9b0a5"
	},
	"resources": {
		"5f1ea7e8-ee26-46c9-91dc-cd002cb9b0a5": {
			"type": "stf.prefab",
			"referenced_resources": ["0e2e767b-2f90-4739-ad78-486b378ba051"],
			"root": "1e5775b8-64ae-4cfa-b8dd-ad6a91469d95",
			"nodes": {
				"1e5775b8-64ae-4cfa-b8dd-ad6a91469d95": {
					"name": "Super Awesome Model",
					"enabled": true,
					"trs": [],
					"children": [],
					"components": {
						"2d172a76-e326-44d1-98c3-0c0ee2b15edd": {
							"type": "stf.instance.mesh",
							"enabled": true,
							"mesh": 0
						}
					}
				}
			}
		},
		"0e2e767b-2f90-4739-ad78-486b378ba051": {
			"type": "stf.mesh",
			"referenced_buffers": ["2c04d7f9-96cd-4867-baf3-2a54d4d31a67"],
			"vertex_count": 32000,
			"vertecies": {
				"format": "f32",
				"buffer": 0
			}
		}
	},
	"buffers": {
		"2c04d7f9-96cd-4867-baf3-2a54d4d31a67": {
			"type": "stf.buffer.included",
			"index": 0
		}
	}
}
----
====

== License
This repository is licensed under **CC-BY-4.0** (<https://creativecommons.org/licenses/by/4.0/>)
