= STF: Documentation
:homepage: https://github.com/emperorofmars/stf
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

**Squirrel Transfer Format - Modular 3D Interchange Format** [version 0.0.0]

Intended for (not only) game development use-cases.

[cols=3*, frame=none, grid=none]
[%autowidth]
|===
|**Available for:**
|**https://github.com/emperorofmars/stf_blender[Blender]**
|**https://github.com/emperorofmars/stf_unity[Unity]**
|===

⭐ Star this repo if you would like to not loose half your work between export and import! ⭐

This repository hosts the documentation for the core format and core modules.

---

Similar to the concept of GLTF 2.0, this format consists of a Json definition and binary buffers. However, this format is firmly intended for interchange & integrity, not runtime loading optimization.
Game-engines are responsible for runtime optimization, not the 3d file format or 3d modeling tool!

It doesn't hard-code any specific resource types like GLTF. It consists of a structure of resources which get identified by a 'type' property. Support for any arbitrary type gets implemented by modules, which should be pluggable and hot-loadable.

.Core Principles
* Highly modular and extensible
* Doesn't impose any descisions on artists and game-developers
* Prioritizes developer-experience over performance
* Maximizes development speed for STF implementations and additional third party modules

---

[cols=3*, frame=none, grid=none]
[%autowidth]
|===
|**link:./docoumentation/stf_documentation.adoc[Core Format Documentation]**
|**link:./docoumentation/modules.adoc[Modules Documentation]**
|**link:./stf_roadmap.adoc[Roadmap]**
|===

---

Previously, a proof-of-concept for such a format has been made here: https://github.com/emperorofmars/stf-unity-poc[Repository Link]

---

.Minimal example Json definition
[%collapsible]
====
[,json]
----
{
	"stf": {
		"version_major": 0,
		"version_minor": 0,
		"meta": {
			"asset_name": "STF Example 1"
		},
		"profiles": [
			"compatibility_wide"
		],
		"metric_multiplier": 1.0,
		"root": "5f1ea7e8-ee26-46c9-91dc-cd002cb9b0a5"
	},
	"resources": {
		"5f1ea7e8-ee26-46c9-91dc-cd002cb9b0a5": {
			"type": "stf.prefab",
			"referenced_resources": ["0e2e767b-2f90-4739-ad78-486b378ba051"]
			"root": "1e5775b8-64ae-4cfa-b8dd-ad6a91469d95"
			"nodes": {
				"1e5775b8-64ae-4cfa-b8dd-ad6a91469d95": {
					"type": "stf.node.spatial",
					"name": "Some Node",
					"enabled": true,
					"trs": [],
					"children": ["eb25c8e4-8e0a-4ac2-8f51-1b87e22afcd9"],
					"components": {}
				}
				"eb25c8e4-8e0a-4ac2-8f51-1b87e22afcd9": {
					"type": "stf.instance.mesh",
					"name": "Super Awesome Model",
					"enabled": true,
					"trs": [],
					"children": [],
					"mesh": "0e2e767b-2f90-4739-ad78-486b378ba051",
					"components": {}
				}
			}
		},
		"0e2e767b-2f90-4739-ad78-486b378ba051": {
			"type": "stf.mesh",
			"referenced_buffers": ["2c04d7f9-96cd-4867-baf3-2a54d4d31a67"]
			"vertex_count": 32000,
			"vertex_width": 4,
			"vertex_indices_width": 4,
			"vertices": "2c04d7f9-96cd-4867-baf3-2a54d4d31a67"
		}
	},
	"buffers": {
		"2c04d7f9-96cd-4867-baf3-2a54d4d31a67": {
			"type": "stf.buffer.included",
			"index": 0
		}
	}
}
----
====

== License
This repository is licensed under **CC-BY-4.0** (<https://creativecommons.org/licenses/by/4.0/>)
