= STF: Documentation
:homepage: https://github.com/emperorofmars/stf
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

**Squirrel Transfer Format - Experimental Modular 3D Interchange Format** [version 0.0.0]

Intended for (not only) game development use-cases.

[cols=4*, frame=none, grid=none]
[%autowidth]
|===
|**In development for:**
|**https://github.com/emperorofmars/stf_blender[Blender]**
|**https://github.com/emperorofmars/stf_unity[Unity]**
|Godot (TBD soon)
|===

Very relevant future implementation targets include: 3dsMax, Unreal Engine, Maya, Bevy, BabylonJs, ...

---

This repository hosts the documentation for the STF format and core modules.

[cols=3*, frame=none, grid=none]
[%autowidth]
|===
|**link:./docoumentation/stf_documentation.adoc[Core Format Documentation]**
|**link:./docoumentation/modules.adoc[Modules Documentation]**
|**link:./stf_roadmap.adoc[Roadmap]**
|===

== Concept
STF by itself is merely a shell format. It provides a framework for different modules to parse and serialize resourses.

Resources are stored as Json-objects, identified by a unique ID. Resources can reference binary buffers and each other.

A few modules, including but not limited to `stf.prefab`, `stf.node`, `stf.mesh` and `stf.material`, are provided by default.

Additional modules can be easily implemented by third parties. Each STF implementation provides an easy and convenient way to hot-load module-plugins.

Similar to glTF 2.0, an STF file consists of a Json definition and binary data. Contrary to glTF, STF is firmly intended for interchange of 3d assets, not runtime loading or asset-streaming.
Game-engines are responsible for runtime optimization, not the 3d file format or 3d modeling tool.

.Minimal example Json definition
[%collapsible]
====
[,json]
----
include::examples/minimal.json[]
----
====

---

Previously, a proof-of-concept for such a format has been made here: https://github.com/emperorofmars/stf-unity-poc[Repository Link]

== License
This repository is licensed under **CC-BY-4.0** (<https://creativecommons.org/licenses/by/4.0/>)
