= STF: Documentation
Mars <mars@squirrel.pub>
v0.0.7
:homepage: https://stfform.at
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

**Squirrel Transfer Format - Experimental Modular 3D Interchange Format** [version {revnumber}]

Intended for (not only) game development use-cases.

[cols=4*, frame=none, grid=none]
[%autowidth]
|===
|**In development for:**
|**https://github.com/emperorofmars/stf_blender[Blender]**
|**https://github.com/emperorofmars/stf_unity[Unity]**
|**https://github.com/emperorofmars/stf_godot[Godot]**
|===
_Try to import this https://squirrelbite.itch.io/stf-avatar-showcase[example model]!_

Relevant future implementation targets include: 3dsMax, Unreal Engine, Maya, Bevy, BabylonJs, ...

---

This repository hosts the documentation for the STF format and core modules.

[cols=3*, frame=none, grid=none]
[%autowidth]
|===
|**link:./docoumentation/stf_documentation.adoc[STF Format Documentation]**
|**link:./docoumentation/modules.adoc[Core Modules Documentation]**
|**link:./stf_roadmap.adoc[Roadmap]**
|===

== Concept
STF by itself is merely a shell format. It provides a framework for different modules to parse and serialize resourses.

Resources are stored as Json-objects, identified by a unique ID. Resources can reference binary buffers and each other.

A few modules, including but not limited to `stf.prefab`, `stf.mesh`, `stf.material` or `stf.image`, are provided by default.

Additional modules can be easily implemented by third parties. Each STF implementation provides an easy and convenient way to hot-load module-plugins.

Similar to glTF 2.0, an STF file consists of a Json definition and binary data. Contrary to glTF, STF is firmly intended for interchange of 3d assets, not runtime loading or asset-streaming.
Game-engines are responsible for runtime optimization, not the 3d file format or 3d modeling tool.


//.Minimal example Json definition
//[%collapsible]
//====
//[,json]
//----
//include::examples/minimal.json[]
//----
//====

.Minimal example Json definition
[%collapsible]
====
[,json]
----
{
	"stf": {
		"version_major": 0,
		"version_minor": 0,
		"root": "979c1726-222d-4184-89b1-72f9b2c82d60",
		"profiles": [],
		"asset_info": {
			"asset_name": "Default Cube"
		},
		"generator": "stf_blender",
		"generator_version": "0.0.7",
		"timestamp": "2025-08-04T16:43:03.324405+00:00",
		"metric_multiplier": 1
	},
	"resources": {
		"5ced8683-2dff-49de-aefe-3f02c4856e86": {
			"type": "stf.material",
			"name": "Material",
			"properties": {
				"albedo.color": {
					"type": "color",
					"values": [
						[
							0.800000011920929,
							0.800000011920929,
							0.800000011920929,
							1.0
						]
					]
				},
				"roughness.value": {
					"type": "float",
					"values": [
						0.5
					]
				},
				"metallic.value": {
					"type": "float",
					"values": [
						0.0
					]
				}
			},
			"style_hints": [
				"realistic",
				"pbr"
			],
			"shader_targets": {
				"stfblender": [
					"ShaderNodeBsdfPrincipled"
				]
			}
		},
		"89abf95c-575c-4033-adbc-fffe3f59cdb9": {
			"type": "stf.mesh",
			"name": "Cube",
			"material_slots": [
				"5ced8683-2dff-49de-aefe-3f02c4856e86"
			],
			"float_width": 4,
			"indices_width": 1,
			"vertices": "c69104d6-55a9-4460-a8fc-e2f3a70da3eb",
			"face_corners": "214dd09d-b2eb-4b1f-83bb-c1650222a897",
			"splits": "a7ca9d09-169f-4f65-8af5-265a3e1c1128",
			"split_normals": "497cd907-6bbf-4017-bbf4-bdb57f34a6b4",
			"uvs": [
				{
					"name": "UVMap",
					"uv": "f88f80c6-4b95-4103-88d6-056af49e454b"
				}
			],
			"tris": "f705415c-93c5-48d1-8c12-fa6fc6a976b1",
			"material_indices_width": 1,
			"faces": "42b4c79a-12b9-4fc9-97b0-518bcdef6043",
			"material_indices": "e443faf5-38d0-485a-8f5f-30735c49bf2c",
			"sharp_face_indices": "9c25f6ef-f33b-4aa7-9860-da7427d01bdb",
			"lines": "3d232b23-6deb-41ad-b09e-5805869fff1c",
			"sharp_edges": "cc4206c5-2ff7-4d28-9e90-f4d3c6a8130a",
			"components": [
				"4ab71531-2a97-4d63-b574-3ab760290f4a"
			]
		},
		"4ab71531-2a97-4d63-b574-3ab760290f4a": {
			"type": "stfexp.mesh.seams",
			"indices_width": 1,
			"referenced_buffers": [
				"29e557ab-6f20-4302-9396-a2287cda0b6e"
			],
			"seams": "29e557ab-6f20-4302-9396-a2287cda0b6e"
		},
		"9742257e-e1b3-424f-882f-33c44c746d98": {
			"type": "stf.instance.mesh",
			"name": "",
			"mesh": "89abf95c-575c-4033-adbc-fffe3f59cdb9"
		},
		"25f8b224-46a3-404c-a15a-8594f2c9e8fc": {
			"type": "stf.node",
			"name": "Cube",
			"children": [],
			"trs": [
				[
					0.0,
					0.0,
					-0.0
				],
				[
					0.0,
					0.0,
					-0.0,
					1.0
				],
				[
					1.0,
					1.0,
					1.0
				]
			],
			"instance": "9742257e-e1b3-424f-882f-33c44c746d98"
		},
		"53650c64-eb81-4873-a4f0-4e274c02597f": {
			"type": "stf.node",
			"name": "Light",
			"children": [],
			"trs": [
				[
					4.076245307922363,
					5.903861999511719,
					-1.0054539442062378
				],
				[
					0.16907574236392975,
					0.7558803558349609,
					-0.27217137813568115,
					0.570947527885437
				],
				[
					1.0,
					1.0,
					0.9999999403953552
				]
			]
		},
		"57d85e39-1994-4604-b4fc-4acd76a5f635": {
			"type": "stf.node",
			"name": "Camera",
			"children": [],
			"trs": [
				[
					7.358891487121582,
					4.958309173583984,
					6.925790786743164
				],
				[
					0.483536034822464,
					0.33687159419059753,
					-0.20870360732078552,
					0.7804827094078064
				],
				[
					1.0,
					1.0,
					1.0
				]
			]
		},
		"979c1726-222d-4184-89b1-72f9b2c82d60": {
			"type": "stf.prefab",
			"name": "Collection",
			"root_nodes": [
				"25f8b224-46a3-404c-a15a-8594f2c9e8fc",
				"53650c64-eb81-4873-a4f0-4e274c02597f",
				"57d85e39-1994-4604-b4fc-4acd76a5f635"
			],
			"animations": []
		}
	},
	"buffers": {
		"c69104d6-55a9-4460-a8fc-e2f3a70da3eb": {
			"type": "stf.buffer.included",
			"index": 0
		},
		"214dd09d-b2eb-4b1f-83bb-c1650222a897": {
			"type": "stf.buffer.included",
			"index": 1
		},
		"a7ca9d09-169f-4f65-8af5-265a3e1c1128": {
			"type": "stf.buffer.included",
			"index": 2
		},
		"497cd907-6bbf-4017-bbf4-bdb57f34a6b4": {
			"type": "stf.buffer.included",
			"index": 3
		},
		"f88f80c6-4b95-4103-88d6-056af49e454b": {
			"type": "stf.buffer.included",
			"index": 4
		},
		"f705415c-93c5-48d1-8c12-fa6fc6a976b1": {
			"type": "stf.buffer.included",
			"index": 5
		},
		"42b4c79a-12b9-4fc9-97b0-518bcdef6043": {
			"type": "stf.buffer.included",
			"index": 6
		},
		"e443faf5-38d0-485a-8f5f-30735c49bf2c": {
			"type": "stf.buffer.included",
			"index": 7
		},
		"9c25f6ef-f33b-4aa7-9860-da7427d01bdb": {
			"type": "stf.buffer.included",
			"index": 8
		},
		"3d232b23-6deb-41ad-b09e-5805869fff1c": {
			"type": "stf.buffer.included",
			"index": 9
		},
		"cc4206c5-2ff7-4d28-9e90-f4d3c6a8130a": {
			"type": "stf.buffer.included",
			"index": 10
		},
		"29e557ab-6f20-4302-9396-a2287cda0b6e": {
			"type": "stf.buffer.included",
			"index": 11
		}
	}
}
----
====

---

Previously, a proof-of-concept for such a format has been made here: https://github.com/emperorofmars/stf-unity-poc[Repository Link]

== License
This repository is licensed under **CC-BY-4.0** (<https://creativecommons.org/licenses/by/4.0/>)
