= Comparison to other Formats
Mars <mars@squirrel.pub>
:homepage: https://stfform.at
:keywords: stf, 3d, fileformat, format, interchange, interoperability
:hardbreaks-option:
:idprefix:
:idseparator: -
:library: Asciidoctor
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
ifdef::env-codeberg[:relfilesuffix: .adoc]

== FBX
FBX is the industry standard. Unfortunately it is not extensible, undocumented, and its official implementation is proprietary.
Many open-source projects, like Blender and Godot, rely on unofficial reverse engineered implementations, with varying success.

== glTF 2.0
Similar to glTF 2.0, an STF file consists of a Json definition and binary data.
Contrary to glTF, STF is firmly intended for interchange of 3d assets, not runtime loading or asset-streaming.

GLTF is intended to be delivered to the end-user and loaded directly into video-memory.
STF is intended to be delivered to a games-developer or artist.

Game-engines are responsible for runtime optimization (at asset-import and/or build time), not the 3d file format or 3d modeling tool.

== USD
The https://openusd.org/release/usdfaq.html#isn-t-usd-just-another-file-format[official OpenUSD FAQ] does a better job at explaining this, than the author of this file ever could.

USD can instantiate assets from other regular 3D file-formats, similar to how game-engine scenes can instantiate assets from imported 3d models.

USD does not replace regular 3d file-formats and vice versa.
